version: '3.8'

volumes:
  jenkins-home:

services:
  jenkins:
    image: jenkins/jenkins:latest
    container_name: jenkinsCIS
    build: .
    restart: unless-stopped
    privileged: true
    user: root
    ports:
      - target: 8080
        published: 8080
        protocol: tcp
        mode: host
      - 50000:50000
    volumes:
      - jenkins-home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
